server:
  port: 8084

grpc:
  server:
    port: 9084
    enable-reflection: true

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://admin:adminpassword@localhost:27017/ecommerce?authSource=admin
      database: ecommerce
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  cache:
    type: redis
    redis:
      time-to-live: 1800000 # 30 minutes in milliseconds
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: product-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ecommerce.shared.models.events"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Metrics Configuration
ecommerce:
  metrics:
    enabled: true
    application-name: product-service
    application-version: 1.0.0
    environment: ${ENVIRONMENT:development}
    jvm-metrics-enabled: true
    business-metrics-enabled: true
    database-metrics-enabled: false
    cache-metrics-enabled: true
    method-timing-enabled: true

app:
  kafka:
    topics:
      product-events: product-events

# Tracing Configuration
tracing:
  enabled: true
  jaeger:
    endpoint: http://localhost:14250
  otlp:
    endpoint: http://localhost:4317
  sampling:
    ratio: 0.1 # Sample 10% of traces
  export:
    timeout: 30s
    batch:
      size: 512
      delay: 2s

logging:
  level:
    com.ecommerce: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId}] [%X{tenantId}] [%X{userId}] [%X{traceId}] [%X{spanId}] %logger{36} - %msg%n"
