server:
  port: 8082

grpc:
  server:
    port: 9082
    enable-reflection: true

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth_service
    username: auth_user
    password: auth_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

jwt:
  secret: ${JWT_SECRET:your-secret-key-change-in-production}
  access-token:
    expiration: 3600
  refresh-token:
    expiration: 86400
  issuer: ecommerce-auth-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

app:
  security:
    jwt:
      filter:
        enabled: false

auth:
  token:
    cleanup:
      enabled: true
      # Run every day at 2 AM
      cron-expression: "0 0 2 * * ?"
      # Keep revoked tokens for 30 days
      revoked-token-retention-period: P30D
      batch-size: 1000

logging:
  level:
    com.ecommerce: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId}] [%X{tenantId}] [%X{userId}] %logger{36} - %msg%n"
