apiVersion: 1

datasources:
  - name: Prometheus-Main
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheus-main
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
    secureJsonData: {}

  - name: Prometheus-Federation
    type: prometheus
    access: proxy
    url: http://prometheus-federation:9090
    uid: prometheus-federation
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "60s"
      queryTimeout: "60s"
      httpMethod: "POST"
    secureJsonData: {}
